# Generated by Django 4.2.3 on 2023-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('n', 'new'), ('r', 'rendered'), ('p', 'printed')], default='n'),
        ),
    ]
